theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
markdown: kramdown
usemathjax : true

title: Machine learning with Python
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
email: mustadruben@gmail.com
description: "Course materials and notes for Stanford class CS231n: Convolutional Neural Networks for Visual Recognition."
baseurl: ""
url: "https://rubenmu96.github.io"
github_username: rubenmu96
source: rubenmu96
description: Under work.
relative_links:
  enabled: true
  collections: true
layout: page
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
